### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [RicardoParizotto/qiskit_learn#1]
I recently came across your project qiskit_learn and I noticed that the repository github.com/RicardoParizotto/qiskit_learn currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by RicardoParizotto** [comment]
Thanks Juan, i added a License as requested.

Best,
Ricardo.

Em qui., 5 de set. de 2024 às 12:07, Juan Cruz-Benito <
***@***.***> escreveu:

**Comment by cbjuan** [comment]
Thank you!
